Fixes fatal error when getScreenshot is called and allow to capture screenshots for drivers that implement getScreenshot method (Selenium)
Fatal error: Call to undefined method Behat\Mink\Session::getScreenshot() in ../behat/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/RawMinkContext.php on line 125